configVersion: 1.0.0
componentName: tcpipNetConfig_0
coreVersion: 5.8.2
device: ATSAME54P20A
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: tcpipNetConfig_0
  type: module
  version: ''
- dependencyPackage: ''
  name: net
  type: package
  version: v3.14.4
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments:
    children:
    - children:
      - attributes:
          id: NETCONFIG_MAC_Dependency
        children:
        - children:
          - attributes:
              id: targetComponentID
            children:
            - type: Value
              value: drvExtMacLan865x_0
            type: String
          - attributes:
              id: targetAttachmentID
            children:
            - type: Value
              value: libdrvExtMacLan865x
            type: String
          type: Attributes
        type: DirectDependency
      type: Attachments
    type: tcpipNetConfig_0
  elementPosition: {}
  symbols:
    TCPIP_NETWORK_DEFAULT_DNS_IDX0:
      attributes:
        id: TCPIP_NETWORK_DEFAULT_DNS_IDX0
      children:
      - children:
        - attributes:
            id: tcpipNetConfig_0
            value: 192.168.100.1
          type: Dynamic
        type: Values
      type: String
    TCPIP_NETWORK_DEFAULT_GATEWAY_IDX0:
      attributes:
        id: TCPIP_NETWORK_DEFAULT_GATEWAY_IDX0
      children:
      - children:
        - attributes:
            id: tcpipNetConfig_0
            value: 192.168.100.1
          type: Dynamic
        type: Values
      type: String
    TCPIP_NETWORK_DEFAULT_HOST_NAME_IDX0:
      attributes:
        id: TCPIP_NETWORK_DEFAULT_HOST_NAME_IDX0
      children:
      - children:
        - attributes:
            id: tcpipNetConfig_0
            value: MCHP_LAN865x
          type: Dynamic
        type: Values
      type: String
    TCPIP_NETWORK_DEFAULT_INTERFACE_NAME_IDX0:
      attributes:
        id: TCPIP_NETWORK_DEFAULT_INTERFACE_NAME_IDX0
      children:
      - children:
        - attributes:
            id: tcpipNetConfig_0
            value: LAN865x
          type: Dynamic
        type: Values
      type: String
    TCPIP_NETWORK_DEFAULT_IP_ADDRESS_IDX0:
      attributes:
        id: TCPIP_NETWORK_DEFAULT_IP_ADDRESS_IDX0
      children:
      - children:
        - attributes:
            id: tcpipNetConfig_0
            value: 192.168.100.11
          type: Dynamic
        type: Values
      type: String
    TCPIP_NETWORK_DEFAULT_MAC_ADDR_IDX0:
      attributes:
        id: TCPIP_NETWORK_DEFAULT_MAC_ADDR_IDX0
      children:
      - children:
        - attributes:
            id: tcpipNetConfig_0
            value: 00:04:25:1C:A0:02
          type: Dynamic
        type: Values
      type: String
    TCPIP_NETWORK_DEFAULT_MAC_DRIVER_IDX0:
      attributes:
        id: TCPIP_NETWORK_DEFAULT_MAC_DRIVER_IDX0
      children:
      - children:
        - attributes:
            id: tcpipNetConfig_0
            value: DRV_LAN865X_MACObject
          type: Dynamic
        type: Values
      type: String
    TCPIP_STACK_NETWORK_CONFIG_IDX0:
      attributes:
        id: TCPIP_STACK_NETWORK_CONFIG_IDX0
      children:
      - children:
        - attributes:
            id: tcpipNetConfig_0
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    TCPIP_STACK_NETWORK_CONFIG_NUMBER:
      attributes:
        id: TCPIP_STACK_NETWORK_CONFIG_NUMBER
      children:
      - children:
        - attributes:
            id: tcpipNetConfig_0
            value: '0'
          type: Dynamic
        type: Values
      type: Integer
  userData: {}
