package:
  format-version: "1.0.0"
  name: "net_10base_t1s"
  version: "1.3.1"
  type: "application"
  status: "production"
  
  dependencies:
    - name: "net"
      type: "package"
      version: "3.11.0"      
