format_version: v1.0
configName: FreeRTOS
folderName: tcpip_iperf_lan867x_freertos
frameworkPath: C:\Harmony3
processor: ATSAME54P20A
projectName: tcpip_iperf_lan867x_freertos
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME54_DFP\3.8.234\atdf\ATSAME54P20A.atdf
